FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app_streamlit.py .
COPY data/ ./data/
COPY src/ ./src/
COPY reports/ ./reports/
COPY src/mlops_tp/artifacts/ ./artifacts/   

ENV PORT=8501
ENV PYTHONPATH=/app/src

EXPOSE 8501

CMD ["sh", "-c", "streamlit run app_streamlit.py --server.port=${PORT} --server.address=0.0.0.0"]