FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY data/ ./data/
COPY conftest.py .


COPY src/mlops_tp/artifacts/ ./artifacts/


ENV PYTHONPATH=/app/src
ENV PORT=8000
ENV GIT_PYTHON_REFRESH=quiet

EXPOSE 8000

CMD ["sh", "-c", "uvicorn mlops_tp.api:app --host 0.0.0.0 --port ${PORT}"]