FROM python:3.11-slim

WORKDIR /app

# Copier les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source et les artefacts
COPY src/ ./src/
COPY conftest.py .

# Exposer le port FastAPI
EXPOSE 8000

# Lancer l'API
CMD ["uvicorn", "mlops_tp.api:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "src"]
